<a href="https://colab.research.google.com/github/hmaksudul01/Machine-Learning/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Library

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Import data

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[ : , : -1].values
Y = dataset.iloc[ : , -1].values

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 nan]
 ['Germany' nan 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 55000.0]
 ['France' 35.0 58000.0]
 ['Spain' 30.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[['France' 44.0 72000.0]
 ['Spain' 27.0 nan]
 ['Germany' nan 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 55000.0]
 ['France' 35.0 58000.0]
 ['Spain' 30.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Missing values

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy= 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 64555.555555555555]
 ['Germany' 38.77777777777778 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 55000.0]
 ['France' 35.0 58000.0]
 ['Spain' 30.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[['France' 44.0 72000.0]
 ['Spain' 27.0 64555.555555555555]
 ['Germany' 38.77777777777778 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 55000.0]
 ['France' 35.0 58000.0]
 ['Spain' 30.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding

# Encoding independent variables

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 64555.555555555555]
 [0.0 1.0 0.0 38.77777777777778 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 55000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 30.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 64555.555555555555]
 [0.0 1.0 0.0 38.77777777777778 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 55000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 30.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Encoding Dependent Variables

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [ ]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]
[0 1 0 0 1 1 0 1 0 1]


# Spliting data in Test and Training

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 30.0 52000.0]
 [0.0 1.0 0.0 40.0 55000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 64555.555555555555]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 0.0 1.0 30.0 52000.0]
 [0.0 1.0 0.0 40.0 55000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 64555.555555555555]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 38.77777777777778 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[[0.0 1.0 0.0 38.77777777777778 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(Y_train)

[0 1 0 0 1 1 0 1]
[0 1 0 0 1 1 0 1]


In [ ]:
print(Y_test)

[0 1]
[0 1]


# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -1.174190531496196 -1.2789108471521071]
 [0.0 1.0 0.0 0.13046561461068845 -0.9961629014153054]
 [1.0 0.0 0.0 0.6523280730534422 0.6060754577599042]
 [0.0 0.0 1.0 -0.13046561461068845 -0.430667009941702]
 [0.0 0.0 1.0 -1.5655873753282612 -0.09555833351290005]
 [1.0 0.0 0.0 1.174190531496196 1.2658206644791083]
 [0.0 1.0 0.0 1.4351217607175728 1.6428179254615105]
 [1.0 0.0 0.0 -0.5218624584427538 -0.7134149556785037]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -0.028992358802375107 -1.090412216660906]
 [1.0 0.0 0.0 -0.2609312292213769 0.13482888153190142]]
